# Lab 03 - Extended Exercises on Model Evaluation
## Predicting student performance

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

import scipy as sp

# Data directory
DATA_DIR = "./../../data/"

In [2]:
import requests

exec(requests.get("https://courdier.pythonanywhere.com/get-send-code").content)

npt_config = {
    'session_name': 'lab-05',
    'session_owner': 'mlbd',
    'sender_name': input("Your name: "),
}

Your name:  P

## Introduction
The data has already been cleaned and it comes from 29 students in 3 different groups in a course of 26 weeks.

You already used this data in week 03. 

In this lab you will explore different models to predict the quiz grade.

In [3]:
# Load data
df= pd.read_csv(f'{DATA_DIR}grades_in_time.csv.gz')
send(len(df), 0)
df.head()

   student  week  studying_hours  group  quiz_grade
0        0     0            39.9      3         6.1
1        0     1            32.4      3         7.0
2        0     2            17.5      3         6.9
3        0     3            16.0      3         7.0
4        0     4            15.9      3         7.2

In [4]:
df.describe(include='all')

          student        week  studying_hours       group  quiz_grade
count  810.000000  810.000000      810.000000  810.000000  810.000000
mean    14.500000   13.000000       10.050617    1.933333    6.931975
std      8.660789    7.793693        8.270041    0.772199    1.336888
min      0.000000    0.000000        1.000000    1.000000    1.200000
25%      7.000000    6.000000        5.700000    1.000000    6.400000
50%     14.500000   13.000000        7.800000    2.000000    7.200000
75%     22.000000   20.000000       11.100000    3.000000    7.800000
max     29.000000   26.000000       64.000000    3.000000   10.100000

# Task 1: Predict the quiz grade using the studying hours and the group.
----------
### 1.1 Split the data. 80% to train and the rest to test.

In [5]:
X =  # Missing code
y =  # Missing code

X_train, X_test, y_train, y_test = # Missing code

SyntaxError: invalid syntax (1995112959.py, line 1)

### 1.2 Preprocess the data
Recall that group is a categorical feature.

Hint: Use ColumnTransformer.

In [ ]:
preprocessor = ColumnTransformer([
    ('categorical', # Missing code,
    ('numerical', # Missing code
])
​
preprocessor.fit_transform(X_train)

### 1.3 Create a pipeline (including the preprocessing steps) to predict the quiz grade using the studying hours and the group.

1. Use the model ElasticNet for the regression task.
2. Calculate the mean sqaured error of the prediction. 


Hint: Integrate the ColumnTransformer as a pipeline step

In [ ]:
pipe = Pipeline([
    ('preprocessor', # Missing code),
    ('model', # Missing code )
])

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
error = # Missing code 
send(f"Mean Squared Error = {error}", 13)
print(f"Mean Squared Error = {error}")

### 1.4 Compute the cross validation score

In [ ]:
pipe = Pipeline([
    ('preprocessor', # Missing code),
    ('model', # Missing code )
])

cvscore = # Missing code
send(cvscore, 14)

### 1.5 Does the score in 1.3 differ from the score in 1.4? Why?

In [ ]:
answer = " Missing answer "
send(answer, 15)

### 1.6 What is wrong with data split?

In [ ]:
answer = " Missing answer "
send(answer, 16)

In [104]:
# Missing code

# Task 2: Model Selection

Of course, when training ML models, we want to tune their hyperparameters in order to optimize the performance. In order to tune the hyperparameters of a model, we need to do further splits of our data set.  In the following, we present an incorrect example. Your task is to:
- Explain why it is incorrect. 
- Describe how it could be fixed.

In [ ]:
# We compute a grid search across the following parameter space
parameters = {
    'n_estimators': [20, 50, 100],
    'criterion': ['entropy', 'gini'],
    'max_depth': np.arange(3, 7),
    'min_samples_split': [2],
    'min_samples_leaf': [1],
}

# Perform 10-fold cross-validation to identify the best hyperparameters, selecting the ones with the highest accuracy
clf = GridSearchCV(RandomForestClassifier(random_state=42), parameters, cv=10, scoring=['accuracy', 'roc_auc'], refit='accuracy')
clf.fit(X, y)

In [ ]:
clf.best_params_

In [ ]:
accuracy = clf.cv_results_['mean_test_accuracy'][clf.best_index_]
AUC = clf.cv_results_['mean_test_roc_auc'][clf.best_index_]

print(f'Accuracy for train-validation-test setting: {accuracy:.3f}')
print(f'AUC for train-validation-test setting: {AUC:.3f}')

In [ ]:
# YOUR TURN: Explain why it is incorrect. 
answer = ""
send(answer, 2)

In [ ]:
# YOUR TURN: Describe how it could be fixed.
answer = ""
send(answer, 3)